name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Publish Docker Image
      uses: elgohr/Publish-Docker-Github-Action@2.12
      env:
        EVERYLOT_KEY: ${{ secrets.EVERYLOT_KEY }}
      with:
        name: consindo/everylotbot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: 'EVERYLOT_KEY'

